<?php

namespace Controller;

use Core\Config;
use Model\ApplicationModel;
use Model\UsersModel;
use TexLab\MyDB\DB;
use TexLab\MyDB\DbEntity;
use View\View;

class ApplicationController extends AbstractTableController
{
    protected $tableName = "application";
    protected $usersTable;

    public function __construct(View $view)
    {
        parent::__construct($view);
        $this->table = new ApplicationModel(
            $this->tableName,
            DB::Link([
                'host' => Config::MYSQL_HOST,
                'username' => Config::MYSQL_USER_NAME,
                'password' => Config::MYSQL_PASSWORD,
                'dbname' => Config::MYSQL_DATABASE
            ])
        );

        $this->usersTable = new UsersModel(
            "users",
            DB::Link([
                'host' => Config::MYSQL_HOST,
                'username' => Config::MYSQL_USER_NAME,
                'password' => Config::MYSQL_PASSWORD,
                'dbname' => Config::MYSQL_DATABASE
            ])
        );
    }

    public function actionShow(array $data)
    {
        parent::actionShow($data);
        $this
            ->view
            ->setFolder('application');


//        $this->usersTable->getUsers();

        $this->view->addData(
            [
                "usersList" => $this->usersTable->getUsers(),
                'table' => $this
                    ->table
                    ->reset()
                    ->setPageSize(Config::PAGE_SIZE)
                    ->getApplicationPage($data['get']['page'] ?? 1)
            ]
        );
        
//        print_r($this->usersTable->getUsers());
        // switch ($_SESSION['user']['cod']) {
        //     case 'admin':
        //         $this
        //             ->view
        //             ->setFolder('application')
        //             ->setTemplate('showadmin')
        //             ->setData([
        //                 'table' => $this->table->get(),
        //                 'fields' => array_diff($this->table->getColumnsNames(), ['id']),
        //                 'comments' => $this->table->getColumnsComments(),
        //                 'type' => $this->getClassName()
        //             ]);
        //         break;
        //     case 'user':
        //         $this
        //             ->view
        //             ->setFolder('application')
        //             ->setTemplate('showuser')
        //             ->setData([
        //                 'table' => $this->table->get(),
        //                 'fields' => array_diff($this->table->getColumnsNames(), ['id']),
        //                 'comments' => $this->table->getColumnsComments(),
        //                 'type' => $this->getClassName()
        //             ]);
        //         break;
        // }
    }

    public function actionShowEdit(array $data)
    {
        parent::actionShowEdit($data); // TODO: Change the autogenerated stub

        $this
            ->view
            ->setFolder('application');

        $this->view->addData(
            [
                "usersList" => $this->usersTable->getUsers(),
            ]
        );
    }
}
