<?php

namespace Controller;

use Core\Config;

class ChairmanApplicationController extends ApplicationController

{
    public function actionShow(array $data)
    {
        parent::actionShow($data); // TODO: Change the autogenerated stub
        $this->view
            ->setFolder("chairmanapplication")
            ->addData(
                [
                    "user_id" => $_SESSION['user']['id'],
                    "usersList" => $this->usersTable->getUsers(),
                    'table' => $this
                        ->table
                        ->reset()
                        ->setPageSize(Config::PAGE_SIZE)
                        ->getApplicationPage($data['get']['page'] ?? 1),
                    "currentPage"=> ($data['get']['page'] ?? 1)
                ]
            );
    }
}