<?php


namespace Controller;


use Core\Config;

class LandlordApplicationController extends ApplicationController
{
    public function actionShow(array $data)
    {
        parent::actionShow($data); // TODO: Change the autogenerated stub
        $this->view
            ->setFolder("landlordapplication")
            ->addData(
                [
                    "user_id" => $_SESSION['user']['id'],
                    "usersList" => $this->usersTable->getUsers(),
                    'table' => $this
                        ->table
                        ->reset()
                        ->setPageSize(Config::PAGE_SIZE)
                        ->getApplicationPageUserFilter($data['get']['page'] ?? 1, $_SESSION['user']['id'])
                ]
            );
    }

    public function actionShowEdit(array $data)
    {
        parent::actionShowEdit($data); // TODO: Change the autogenerated stub
        $this
            ->view
            ->setFolder('landlordapplication');

        $this->view->addData(
            [
                "usersList" => $this->usersTable->getUsers(),
            ]
        );
    }

    public function actionAdd(array $data)
    {
        $data['post']['image'] = $_FILES['image']['name'];
        $id = $this->table->add($data['post']);
        $ext = pathinfo($_FILES['image']['name'], PATHINFO_EXTENSION);
        move_uploaded_file($_FILES['image']['tmp_name'], "images/application/$id.$ext");
        $this->redirect('?action=show&type=' . $this->getClassName());
    }

//    public function actionEdit(array $data)
//    {
//        $data['post']['image'] = $_FILES['image']['name'];
//        $id = $data['post']['id'];
//        $ext = pathinfo($_FILES['image']['name'], PATHINFO_EXTENSION);
//        move_uploaded_file($_FILES['image']['tmp_name'], "images/application/$id.$ext");
//        parent::actionEdit($data); // TODO: Change the autogenerated stub
//        $this->redirect('?action=show&type=' . $this->getClassName());
//    }

}